name: setup
description: "Setup bun and dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: current
    - name: setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ".tool'versions"
    - name: install parallel
      shell: bash
      run: brew install parallel
      if: runner.os == 'macOS'
    - name: install dependencies
      run: bun i
      shell: bash
