#!/usr/bin/env bash
# SLangroom-EXec Format Encoder
# This script is used to encode the format of the slangroom-exec command
# into a string that can be used in the slangroom-exec command

function _out() {     printf "$*\n"; }
function _err() { >&2 printf "$*\n"; }

print_help() {
    _err "SLangroom-EXec Format Encoder"
    _err "Encode the parameters into a base64 string for zencode-exec and slangroom-exec.\n"
    _err "\033[1mUsage:\033[0m"
    _err "  $0 [options]\n"
    _err "\033[1mOptions:\033[0m"
    _err "  -c conf               conf filename to read"
    _err "  -s slangroom-contract slangroom-contract filename to read"
    _err "  -d data               data filename to read"
    _err "  -k keys               keys filename to read"
    _err "  -e extra              extra filename to read"
    _err "  -x context            context filename to read"
    _err "  -F filename           lookup files based on a prefix"
    _err "  -v                    Show version compatibility"
    _err "  -h                    Print this help message\n"
    _err "\033[1mExamples:\033[0m"
    _err "  \033[3mslexfe < contract.slang\033[0m"
    _err "        Get a slangroom contract from stdin and produce the slangroom-exec format encode by leaving the lines for the other files empty."
    _err "  \033[3mslexfe -c conf.conf -s contract.slang -d data.json -k keys.json -e extra.json -x context\033[0m"
    _err "        Get the slangroom contract and its inputs file path and produce the slangroom-exec format encode."
    _err "  \033[3mslexfe -F path/to/filename\033[0m"
    _err "        Equal to do slexfe -c path/to/filename.conf -s path/to/filename.slang -d path/to/filename.data.json -k path/to/filename.keys.json -e path/to/filename.extra.json -x path/to/filename.context"
    exit 1
}

strict_check() {
    if [[ ! -f "$1" ]]; then
        _err "File not found: $1"
        exit 1
    fi
}

# Function to encode to base64
encode_base64() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        cat "$1" 2>/dev/null | base64
    else
        cat "$1" 2>/dev/null | base64 -w 0
    fi
}

encode_json_base64() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        jq -c . "$1" 2>/dev/null | base64
    else
        jq -c . "$1" 2>/dev/null | base64 -w 0
    fi
}

# check that jq and getopt are installed

if ! command -v jq &> /dev/null; then
    _err "jq is not installed. Please install jq to use this script."
    exit 1
fi

if ! command -v getopt &> /dev/null; then
    _err "getopt is not installed. Please install getopt to use this script."
    exit 1
fi

# catch use of long flags
if [[ "$1" == --* ]]; then
    _err "\033[1mInvalid option\033[0m: long options like '$1' are not supported.\n"
    _err "Please use -h for help."
    exit 1
fi

# Default values for options
conf=""
slangroom_contract=""
data=""
keys=""
extra=""
context=""

while getopts ":c:s:d:k:e:x:F:hv" opt; do
    case ${opt} in
        c)
            strict_check "${OPTARG}"
            conf=$(encode_base64 "${OPTARG}" "strict");;
        s)
            strict_check "${OPTARG}"
            slangroom_contract=$(encode_base64 "${OPTARG}" "strict");;
        d)
            strict_check "${OPTARG}"
            data=$(encode_json_base64 "${OPTARG}" "strict");;
        k)
            strict_check "${OPTARG}"
            keys=$(encode_json_base64 "${OPTARG}" "strict");;
        e)
            strict_check "${OPTARG}"
            extra=$(encode_json_base64 "${OPTARG}" "strict");;
        x)
            strict_check "${OPTARG}"
            context=$(encode_base64 "${OPTARG}" "strict");;
        F)
            conf=$(encode_base64 "${OPTARG}.conf")
            slangroom_contract=$(encode_base64 "${OPTARG}.slang")
            data=$(encode_json_base64 "${OPTARG}.data.json")
            keys=$(encode_json_base64 "${OPTARG}.keys.json")
            extra=$(encode_json_base64 "${OPTARG}.extra.json")
            context=$(encode_base64 "${OPTARG}.context");;
        v)
            _err "slexfe compatible with zencode_exec@^5.0.0 and slangroom_exec@^1.0.0"
            exit 0 ;;
        h)
            print_help ;;
        \?)
            _err "\033[1mInvalid option\033[0m: -${OPTARG}\n"
            _err "Please use -h for help."
            exit 1 ;;
        :)
            _err "Option -${OPTARG} requires an argument.\n"
            _err "Please use -h for help."
            exit 1 ;;
    esac
done
shift $((OPTIND -1))


# if slangroom-contract is empty, read it from stdin
if [ -z "$slangroom_contract" ]; then
    slangroom_contract=$(encode_base64 -)
fi

# Print the encoded string
_out "${conf}\n${slangroom_contract}\n${data}\n${keys}\n${extra}\n${context}"
